name: RestAssuredTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 18 * * *" # Every day at 6:00 PM UTC
   
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Execute Test
      run: mvn clean test -Dsuite=Suite -X

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0

      with:
       name: Logs 
       path: logs/

  
